Update all the things \o/

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,23 +1,33 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require "fileutils"
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+# path to your application root.
+APP_ROOT = File.expand_path("..", __dir__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-gem list bundler --installed >/dev/null || gem install bundler
-gem list foreman --installed >/dev/null || gem install foreman
-bundle install
+FileUtils.chdir APP_ROOT do
+  # This script is a way to set up or update your development environment automatically.
+  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
+  # Add necessary setup steps to this file.
 
-# Install Javascript dependencies
-yarn install
+  puts "== Installing dependencies =="
+  system! "gem install bundler --conservative"
+  system("bundle check") || system!("bundle install")
 
-# Set up configurable environment variables
-if [ ! -f .env ]; then
-  cp .env.sample .env
-fi
+  # puts "\n== Copying sample files =="
+  # unless File.exist?("config/database.yml")
+  #   FileUtils.cp "config/database.yml.sample", "config/database.yml"
+  # end
 
-# Set up database and add any development seed data
-bundle exec rake db:setup
+  puts "\n== Preparing database =="
+  system! "bin/rails db:prepare"
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! "bin/rails log:clear tmp:clear"
+
+  puts "\n== Restarting application server =="
+  system! "bin/rails restart"
+end
